version: "3.8"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/static
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A product_scraper worker --loglevel=info
    restart: always
    depends_on:
      - redis
      - django

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A product_scraper beat --loglevel=info
    restart: always
    depends_on:
      - redis
      - django

volumes:
  postgres_data:
  static_volume:
